AY2324S1-CS2103T-F11-2/tp

- README.md
+ added team name to README
test commit to trigger workflows for the first time to sync with codecov
> test commit to setup CodeCov

- README.md
The README currently describes the AB3.
The README should be modified to match our own team project.
Let's modify the description of the project and update the GitHub Actions build status badge to reflect the build status of the team repo.
> Update README.md with project description

- docs/index.md
The sitemap index currently describes the AB3.
The sitemap should be modified to match our own team project.
Let's update the GitHub Actions badges and the project description to reflect the team project.
> Update sitemap index

- src/main/java/seedu/address/model/person/Vendor.java
- src/test/java/seedu/address/model/person/VendorTest.java
- src/test/java/seedu/address/testutil/VendorUtil.java
Implemented Guest class. Guest inherits from Person.
Implemented trivial test class for Guest.
No deletions made to existing codebase.
> Create Vendor class

- docs/DeveloperGuide.md
The product scope details information about AddressBook.
WedLog has a significantly different target audience and value proposition.
Let's change the product scope to reflect WedLog's target audience and value proposition.
This will make the developer's guide more relevant for WedLog.
> Update product scope in Developer Guide

- docs/DeveloperGuide.md
Currently, the developer guide contains minimal non-functional requirements (NFRs).
The developer guide's NFRs should cover the full requirements of the product and should be documented.
Let's add more NFRs based on our projection discussions.
This will identify our NFRs for future reference. Partially addresses #9.
> Update DG NFRs

- docs/UserGuide.md
update the UG to add guides for viewing all guests or one guest. Followed Joe's format.
> update UG: view guest(s)

- docs/DeveloperGuide.md
Edit the DG to be called WedLog DG
Add the use cases
> Update DG use case section

- docs/DeveloperGuide.md
Update Glossary and Appendix section of DG.
> update DG: Glossary and Appendix

- docs/AboutUs.md
- docs/team/wasjoe1.md
Add Joe PPP
Realised I did not PQ the branch.
> Add Joe PPP

- docs/DeveloperGuide.md
Fixed minor typo in the DG user stories
> DG: Fix user stories cosmetic issue

- docs/UserGuide.md
- src/main/java/wedlog/address/logic/parser/ParserUtil.java
- src/main/java/wedlog/address/model/person/DietaryRequirements.java
- src/test/java/wedlog/address/logic/parser/ParserUtilTest.java
- src/test/java/wedlog/address/model/person/DietaryRequirementsTest.java
- create the enum values: NONE, EXIST, NULL in Dietary requirements
- create the isNone method for easier access to find out if the DR is none or not
- ensure parserUtil takes in the right values for dietary requirements
- edit the UG so users will know how to state dietary requirements
> Edit dietary requirements

- src/main/java/wedlog/address/logic/commands/GuestListCommand.java
- src/main/java/wedlog/address/logic/commands/VendorListCommand.java
- src/test/java/wedlog/address/logic/commands/GuestListCommandTest.java
- src/test/java/wedlog/address/logic/commands/VendorListCommandTest.java
- created GuestList and VendorList commands
- created respective test cases
> Implement `GuestList` & `VendorList` commands

- src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
> Minor nit to resolve guest delete

- docs/DeveloperGuide.md
- docs/diagrams/EditExecuteSequenceDiagram.puml
- docs/diagrams/EditParseSequenceDiagram.puml
Partially addresses #147.
* Add edit feature documentation
* Add relevant sequence diagrams
> DG: Add edit feature

- docs/UserGuide.md
It's slightly unintuitive to use the user guide with no numbering to the sections.
Let's add numbering to each section and cluster similar commands to make the user guide easier to use.
> UG: Add numbering

- src/main/java/wedlog/address/MainApp.java
- src/main/java/wedlog/address/ui/MainWindow.java
> Fix exception on application startup

- src/main/java/wedlog/address/model/tag/GuestDietaryPredicate.java
- src/main/java/wedlog/address/model/tag/TagPredicate.java
- src/test/java/wedlog/address/model/tag/GuestDietaryPredicateTest.java
- src/test/java/wedlog/address/model/tag/TagPredicateTest.java
Update DR and Tag fields to filter using allMatch.
> Update tag fields to be allMatch

- docs/UserGuide.md
PED is tomorrow.
Let's make minor edits to the UG for better viewing during PED.
> Update UG: Minor edits

- docs/UserGuide.md
Add _ to dietary requirement parameters
> Update UG: Underscore DR

- docs/team/samuelim01.md
The Project Portfolio Page for Samuel is empty.
At the end of the project each student is required to submit a Project Portfolio Page.
Let's document the contributions made by Samuel.
> Docs: Update PPP for Samuel

- docs/UserGuide.md
> UG: Fix broken Appendix A links

- docs/team/wasjoe1.md
> Update ppp Joe

- docs/team/wasjoe1.md
> Branch update ppp

- docs/DeveloperGuide.md
The Developer Guide lacks acknowledgements for sources of all reused/adapted ideas, code, documentation, and third-party libraries.
Let's update the DG to include acknowledgements.
> DG: Add code acknowledgements

- docs/DeveloperGuide.md
The Developer Guide lacks instructions for the tester to go through the features. Fixes #258.
Let's update Appendix B to cover all user-testable features, in accordance with the [requirements](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-deliverables.html#deliverable-developer-guide-dg).
> DG: Update Appendix B

- src/main/java/wedlog/address/model/util/SampleDataUtil.java
> SampleDataUtil: Add sample guest and vendor data

- docs/DeveloperGuide.md
- docs/diagrams/UiClassDiagram.puml
Let's improve the formatting of the DG by:
* Standardizing headers
* Improving use case formatting
* Adding a contents page
* Adding numbering to headers
* Swapping the order of the add and delete features under implementation
* Updating the UiClassDiagram
> DG: Improve formatting

- src/main/java/wedlog/address/MainApp.java
In preparation for the v1.4 release, let's update the version number in`MainApp.java` from 1.3.0 to 1.4.0.
> Update version number in main app to 1.4

- docs/team/samuelim01.md
Let's update the PPP to _conform_ to Keagan and Shannon.
> Reformat PPP (Samuel)
