AY2324S1-CS2103T-F11-2/tp

docs/UserGuide.md

Currently, the user guide doesn't contain v1.2 specific commands.
The user guide should cover the complete detailed description of the intended behavior of the product at v1.2.
Let's add the `vendor add` and `vendor delete` commands into the user guide. This partially addresses #8.

UG: Add `vendor add` and `vendor delete`

---

docs/UserGuide.md

The user guide does not specify expected behavior when WedLog is faced with erroneous inputs that do not fall under a specific command.
When users are faced with these behaviours, they may not understand the reason why.
Let's add a section that details the expected output for different types of input errors that are not tied to a specific command.

Add Appendix A: Miscellaneous error message to User Guide

---

docs/UserGuide.md

Currently, the user guide doesn't contain all v1.2 specific commands.
The user guide should cover the complete detailed description of the intended behavior of the product at v1.2.
Let's add the `help` command into the user guide. This partially addresses #8.

UG: Add `help`

---

src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/model/ModelManagerTest.java
src/test/java/seedu/address/testutil/AddressBookBuilder.java
src/test/java/seedu/address/testutil/TypicalGuests.java

The model lacks methods to add, remove, set and display guests and vendors. Fixes #28.
Let's
* Add the methods to Model to enforce the need for such methods
* Add the methods to ModelManager to implement the methods
* Add the relevant test methods for the new methods
* Modify AddCommandTest.ModelStub with modified Model requirements
The following guest methods (and their corresponding person/vendor methods) have been added to tests:

Model: Add `guest` and `vendor` methods

---

docs/UserGuide.md
src/main/java/wedlog/address/logic/commands/VendorAddCommand.java
src/main/java/wedlog/address/logic/parser/VendorAddCommandParser.java
src/main/java/wedlog/address/logic/parser/VendorCommandParser.java
src/main/java/wedlog/address/model/person/Vendor.java
src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
src/test/java/wedlog/address/logic/commands/VendorAddCommandIntegrationTest.java
src/test/java/wedlog/address/logic/commands/VendorAddCommandTest.java
src/test/java/wedlog/address/logic/parser/VendorAddCommandParserTest.java
src/test/java/wedlog/address/logic/parser/VendorCommandParserTest.java
src/test/java/wedlog/address/testutil/TypicalVendors.java
src/test/java/wedlog/address/testutil/VendorBuilder.java

Resolves #59.
Currently, the VendorAddCommand throws an exception when it is executed.
Let's implement the logic of executing a VendorAddCommand.
This will allow users to add vendors to WedLog

Implement `vendor add`

---

src/main/java/wedlog/address/logic/Messages.java
src/main/java/wedlog/address/logic/commands/VendorAddCommand.java
src/main/java/wedlog/address/logic/commands/VendorDeleteCommand.java
src/main/java/wedlog/address/logic/parser/VendorCommandParser.java
src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
src/test/java/wedlog/address/logic/commands/VendorDeleteCommandTest.java

Currently, the VendorDeleteCommand throws an exception when it is executed.
Let's implement the logic of executing a VendorDeleteCommand.
- update constructor in VendorDeleteCommand
- update execute method in VendorDeleteCommand
- add equals method in VendorDeleteCommand
- add toString method in VendorDeleteCommand
- add MESSAGE_INVALID_VENDOR_DISPLAYED_INDEX message in Messages
- create VendorDeleteCommand class and add tests
- add showVendorAtIndex method in CommandTestUtil
This will allow users to delete vendors from the vendor list by specifying the index.
Resolves #60.

Implement `vendor delete`

---

src/main/java/wedlog/address/logic/Messages.java
src/main/java/wedlog/address/logic/commands/GuestAddCommand.java
src/main/java/wedlog/address/logic/commands/GuestDeleteCommand.java
src/main/java/wedlog/address/logic/parser/GuestDeleteCommandParser.java
src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
src/test/java/wedlog/address/logic/commands/GuestDeleteCommandTest.java
src/test/java/wedlog/address/logic/parser/GuestDeleteCommandParserTest.java

Currently, the GuestDeleteCommand throws an exception when it is executed.
Let's implement the logic of executing a GuestDeleteCommand.
- update constructor in GuestDeleteCommand
- update execute method in GuestDeleteCommand
- add equals method in GuestDeleteCommand
- add toString method in GuestDeleteCommand
- add MESSAGE_INVALID_GUEST_DISPLAYED_INDEX message in Messages
- create GuestDeleteCommandTest class and add tests
- add showGuestAtIndex method in CommandTestUtil
This will allow users to delete guests from the guest list by specifying the index.
Resolves #54.

Implement `guest delete`

---

src/main/java/wedlog/address/model/person/Guest.java
src/main/java/wedlog/address/storage/JsonAdaptedGuest.java
src/test/java/wedlog/address/model/person/GuestTest.java
src/test/java/wedlog/address/storage/JsonAdaptedGuestTest.java
src/test/java/wedlog/address/testutil/TypicalGuests.java

Currently, dietary requirements can be stored as null in `addressbook.json`. `JsonAdaptedGuest` will catch this can throw an exception, causing data to be unable to be loaded.
Let's prevent `JsonAdaptedGuest` from throwing an exception upon a null dietary requirement, and allow `Guest` to be constructed with a null dietary requirement.

Fix: loading data from local storage

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/diagrams/ArchitectureSequenceDiagram.puml
docs/diagrams/LogicClassDiagram.puml
docs/diagrams/ParserClasses.puml

The User Guide lacks the `help` and `exit` command. Let's add them back in.

UG: Add `help` and `exit` command

---

src/main/java/wedlog/address/logic/commands/EditCommand.java
src/main/java/wedlog/address/logic/parser/GuestAddCommandParser.java
src/main/java/wedlog/address/logic/parser/ParserUtil.java
src/main/java/wedlog/address/logic/parser/VendorAddCommandParser.java
src/main/java/wedlog/address/model/person/Guest.java
src/main/java/wedlog/address/model/person/Person.java
src/main/java/wedlog/address/storage/JsonAdaptedGuest.java
src/main/java/wedlog/address/storage/JsonAdaptedPerson.java
src/main/java/wedlog/address/ui/GuestCard.java
src/main/java/wedlog/address/ui/VendorCard.java
src/test/java/wedlog/address/storage/JsonAdaptedGuestTest.java
src/test/java/wedlog/address/storage/JsonAdaptedPersonTest.java
src/test/java/wedlog/address/storage/JsonAdaptedVendorTest.java
src/test/java/wedlog/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/wedlog/address/testutil/GuestBuilder.java
src/test/java/wedlog/address/testutil/GuestUtil.java
src/test/java/wedlog/address/testutil/PersonBuilder.java
src/test/java/wedlog/address/testutil/PersonUtil.java
src/test/java/wedlog/address/testutil/VendorBuilder.java
src/test/java/wedlog/address/testutil/VendorUtil.java

Phone, Email, and Address are optional fields in Person, represented as null if the Person does not have that field. TableNumber is an optional field implemented similarly in Guest.
Let's wrap the fields in Optional, e.g. from Phone to Optional<Phone>. If the Person does not have that field, it is stored as Optional#empty().
This makes it clearer which fields in Person are optional, and enforces that the absence of the field is handled in relevant methods.

Wrap optional fields in `Optional`

---

src/main/java/wedlog/address/logic/parser/GuestAddCommandParser.java
src/main/java/wedlog/address/logic/parser/VendorAddCommandParser.java
src/main/java/wedlog/address/model/person/Phone.java
src/test/java/wedlog/address/logic/LogicManagerTest.java
src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
src/test/java/wedlog/address/logic/parser/GuestAddCommandParserTest.java
src/test/java/wedlog/address/logic/parser/VendorAddCommandParserTest.java
src/test/java/wedlog/address/testutil/TypicalGuests.java
src/test/java/wedlog/address/testutil/TypicalVendors.java

Resolves #125.
Testcases for `vendor add` and `guest add` are in-comprehensive and structured disorderly.
Let's,
* Add more comprehensive testing for the two commands
* Improve differentiability of the tests for the two commands by renaming the test Vendor and Guest object.

Improve testcases for `vendor add` and `guest add` commands

---

build.gradle

By default, assertions are disabled. This could create a situation where one thinks that all assertions are verified when they in fact are not being checked. According to [the project details](https://nus-cs2103-ay2324s1.github.io/website/schedule/week10/project.html#3-start-the-next-iteration), assertions should be enabled in the gradle file.
Let's modify build.gradle to enable assertions.

build.gradle: Enable assertions

---

src/main/java/wedlog/address/logic/parser/GuestEditCommandParser.java
src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
src/test/java/wedlog/address/logic/parser/GuestEditCommandParserTest.java
src/test/java/wedlog/address/logic/parser/VendorEditCommandParserTest.java

`guest edit` function results in an exception when an empty string is passed as a name value.
Let's,
* Update implementation of `guest edit` to display an error message when provided with an invalid name value.
* Update test cases to detect this bug in the future.

Fix `guest edit` bug

---

src/main/java/wedlog/address/model/person/UniqueGuestList.java
src/test/java/wedlog/address/logic/LogicManagerTest.java
src/test/java/wedlog/address/model/AddressBookTest.java
src/test/java/wedlog/address/model/ModelManagerTest.java
src/test/java/wedlog/address/model/person/UniqueGuestListTest.java
src/test/java/wedlog/address/testutil/TypicalGuests.java

Dietary statistics currently displays the meal counts of all guests. Guests with empty dietary requirement fields are counted under `regular`.
Let's exclude Guests with `r/unknown` and `r/no` from the dietary statistics, since no meals should be ordered for them.

Fix minor bug in diet statistics

---

src/main/java/wedlog/address/model/person/Name.java
src/test/java/wedlog/address/model/person/NameTest.java
src/test/java/wedlog/address/model/person/PersonTest.java
src/test/java/wedlog/address/model/person/VendorTest.java

Name is case sensitive, which means that two names like `John` and `john` are considered different names.
This is inconsistent with other sections of the code base, such as the `GuestFilterCommand` which is case-insensitive. It is also unintuitive.
Let's update the equality of name to be case insensitive.
This will also update the functionality of Person#isSamePerson, preventing users from adding two users with full names that only differ in case.

Name: Make name equality case insensitive

---

src/main/java/wedlog/address/logic/Messages.java
src/main/java/wedlog/address/logic/commands/ClearCommand.java
src/main/java/wedlog/address/logic/commands/GuestDeleteCommand.java
src/main/java/wedlog/address/logic/commands/GuestEditCommand.java
src/main/java/wedlog/address/logic/commands/GuestListCommand.java
src/main/java/wedlog/address/logic/commands/VendorDeleteCommand.java
src/main/java/wedlog/address/logic/commands/VendorEditCommand.java
src/main/java/wedlog/address/logic/commands/VendorListCommand.java
src/main/java/wedlog/address/model/tag/DietaryRequirement.java
src/main/resources/view/MainWindow.fxml
src/test/java/wedlog/address/model/tag/DietaryRequirementTest.java

Write better success messages

---

src/main/java/wedlog/address/logic/parser/GuestEditCommandParser.java
src/test/java/wedlog/address/logic/parser/GuestEditCommandParserTest.java

Resolves #225.
- Resolves bug that prevented users from editing multiple dietary requirements.
- Added testcases that check for ability to edit multiple dietary requirements and tags.

Fix guest edit no duplicate dietary bug

---

src/main/java/wedlog/address/commons/core/GuiSettings.java

Resolves #241 
Reduces the default height to 660 so that app window will be fully within the screen on startup.

Fix window size on startup bug

---

docs/UserGuide.md
src/main/java/wedlog/address/model/person/TableNumber.java
src/test/java/wedlog/address/model/person/TableNumberTest.java

Resolves #212 
* Resolves bug that causes an exception to be thrown when an integer greater than `Integer.MAX_VALUE` is input as the table number for a guest.
* Adds test cases for `isValidTableNumber` method to check that an integer greater than `Integer.MAX_VALUE` is an invalid table number.
* Updates UG  to specify additional constraints on valid table numbers (must be between 1 and 2147483647 inclusive)

Fix table number max int bug

---

docs/DeveloperGuide.md

Let's improve the formatting of the DG by:
* Adding numbering for Appendix D sub-headers
* Adding Appendix D to the contents page
* Fixing broken links in the contents page
* Standardizing placement of line breaks

DG: Fix content page formatting

---

docs/UserGuide.md

Let's remove the first part of the tutorial to match the current state of pre-loaded data.

Emergency Fix: Remove `clear` part of tutorial

---

docs/UserGuide.md

The getting started section only provides links from Windows and MacOS.
Let's update the getting started to give a direct link to the installation instead.

UG: Update getting started
